### ISSUE TITLE
Question: How does NBC fit into the rest of the openVA framework?

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#11]
https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/VAmain.r#L290-L308

We notice that there seem to be a few more manipulation hoops happening for `nbc` than occur for other packages; our understanding is that you did not develop `nbc` and that could explain what is happening, but could you provide a little background on these steps, what is happening, and why?

**Comment by richardli** [comment]
yep, someone else maintains nbc4va.
