### ISSUE TITLE
Question/Enhancement: 0.95 default

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#16]
https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/CSMF.r#L58

The documentation states that something defaults to 0.95 but it is unclear what and how to change it.  Furthermore, it seems like this refers to the true value vector, but how then does a vector equal a scalar 0.95?

**Comment by richardli** [comment]
good catch, fixed
