### ISSUE TITLE
Question: Calculation is unclear

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#17]
https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/CSMF.r#L61

https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/CSMF.r#L79

https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/CSMF.r#L96

Could you elaborate on this calculation?  Where does it come from and what is the goal?  Specifically, why is there a factor of 2 in the denominator?

**Comment by sinafala** [comment]
The reference for this is :Popul Health Metr. 2011 Aug 4;9:28. doi: 10.1186/1478-7954-9-28.
Robust metrics for assessing the performance of different verbal autopsy cause assignment methods in validation studies.
