### ISSUE TITLE
Question: Data Conversion in openVA

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#19]
https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/ConvertData.r#L1

Much of this code to convert data standards seems very similar to code contained in CrossVA - what is the intended use case for these functions in `openVA` and how do these functions fit into the pipeline at large?

**Comment by mboyas-mitre** [comment]
Discussion with Sam on the 2/5/19 call suggested that much of this code is deprecated and pre-dates CrossVA, which is the preferred data conversion method going forward.  Proposal to remove the functionality from openVA for maintainability and ease of use.

**Comment by richardli** [comment]
thanks, will coordinate with crossVA to make the transition if necessary. It's also a quite simple function, so that may not be necessary.
