### ISSUE TITLE
Question: Location of InterVA code

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#20]
https://github.com/verbal-autopsy-software/openVA/blob/d6e2af78af59d55ba7dc4421dc1559f1fa94a108/openVA/R/interVA.train.r#L1

Why is this code in `openva` as opposed to either of the two InterVA packages?  Largely this code looks extremely similar to what we reviewed in both of the InterVA packages.

**Comment by richardli** [comment]
yes, but they are not InterVA software functions. So this is to make sure that the boundary of replication InterVA software is clear.
