### ISSUE TITLE
Question/Enhancement: nbc4va optional status

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#21]
https://github.com/verbal-autopsy-software/openVA/blob/6f232ec0ecd5bb0f58b48de5101a25a865df7f7b/openVA/R/CSMF.r#L48

https://github.com/verbal-autopsy-software/openVA/blob/6f232ec0ecd5bb0f58b48de5101a25a865df7f7b/openVA/R/CSMF.r#L175

Why is `nbc4va` an optional dependency to `openVA`, particularly if it is required for certain operations?  It seems like it could be easier just to make it be a required dependency.  Alternatively, we're worried printing the install message to the screen might be too complicated for some users - if it is desired to keep `nbc4va` as an optional dependency, it could be more efficient to explore how to autoinstall the package if these operations are ran.

**Comment by richardli** [comment]
agree, but since we do not maintain nbc4va, we couldn't update it in time when problems in the package is flagged by CRAN. That could risk openVA being removed from CRAN when nbc4va had issues. Thus it's optional.

**Comment by mboyas-mitre** [comment]
That makes sense!  Thanks Richard!
