### ISSUE TITLE
Enhancement: Extra line

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#22]
https://github.com/verbal-autopsy-software/openVA/blob/f16a333a8355582de814e4fef85eda28bc1035ff/openVA/R/stackplot.r#L77

This line to read in a dataset should be unnecessary.  By our understanding, it should be sufficient to just run `data("SampleCategory", envir = environment())` (the line prior to this), which would improve readability and stability of the code.

**Comment by richardli** [comment]
I think this is a CRAN feature that forces packages to load data this way. Removing the second line leads to a CRAN note:

> no visible binding for global variable ‘SampleCategory’

But feel free to suggest alternative options!

**Comment by mboyas-mitre** [comment]
Interesting!  We did some research into this when we refactored the `stackplotVA` code and did not come up with a good alternative.  We'll keep thinking about this but going to close for now;  will let you know if we come up with something else!
