### ISSUE TITLE
Bug: line will always equal 10

### ISSUE THREAD

**Issue by mboyas-mitre** [verbal-autopsy-software/openVA#27]
https://github.com/verbal-autopsy-software/openVA/blob/f16a333a8355582de814e4fef85eda28bc1035ff/openVA/R/VAmain.r#L144

Because the conditions in this calculation are mutually exclusive and the code is always multiplying by 10, this line will, by our estimation, always equal a scalar of 10. We're thinking that this might not be intentional?

**Comment by richardli** [comment]
thanks for catching this.  fixed now.
