### ISSUE TITLE
Enhancement: Add WHO VA Codes to COD Titles

### ISSUE THREAD

**Issue by rrwen** [verbal-autopsy-software/openVA#33]
The cause of death (COD) outputs are in their WHO VA 2016 titles, but there are no codes (e.g. 1.01, 1.02).

## Questions

1. Is there a way to get the WHO VA 2016 codes from openva?
2. Are these codes in the WHO VA 2016 v1.5 standard?

## Use Case

Transforming the WHO VA 2016 codes to other cause of death classifications (e.g. ICD-10, our custom classifications, etc) and matching COD categories that could have different, but similar titles, but the same code.

## Example

I have tried using data(causetextV5) and data(causetext), but it seems that they are mismatched with only 06.02 Liver cirrhosis matching:

```r
# R version 4.3.1
library(openVA)
library(tidyverse)

# Use example from docs to get insilicova results
data(RandomVA3)
test <- RandomVA3[1:200, ]
train <- RandomVA3[201:400, ]
fit1 <- codeVA(data = test, data.type = "customize", model = "InSilicoVA", data.train = train, causes.train = "cause", Nsim=1000, auto.length = FALSE)

# Get top COD predictions
tcod <- getTopCOD(fit1)

# Get title mappings
data(causetext)
data(causetext5V)

# Try to translate titles to VA codes using causetext
mappings <- causetext[,3]
names(mappings) <- causetext[,2]
tcod_remap <- tcod %>% mutate_all(~ recode(., !!!mappings))

# Try to translate titles to VA codes using causetextV5
mappingsv5 <- causetextV5[,3]
names(mappingsv5) <- causetextV5[,2]
tcod_remapv5 <- tcod %>% mutate_all(~ recode(., !!!mappingsv5))

# Show results, only 06.02 Liver cirrhosis was remapped
tcod_remap # not all titles in causetext
tcod_remapv5 # not all titles in causetextV5
```

## Resources

* [WHO VA 2016 v1.5 Titles and Codes](https://github.com/cghr-toronto/icd/blob/main/data/wva2022_v1.csv): csv of codes with their titles extracted from the [WHO VA 2016 v1.5 Manual](https://github.com/cghr-toronto/icd/blob/main/docs/wva2016_manual_v15.pdf) * - I am trying to match the output titles from openva models to these titles/codes*

**Comment by richardli** [comment]
Hi, 

The example you provide is not WHO 2016 data. It's a demo dataset for the "customized" format, so there is no correspondence. 

If you want to check out WHO2016 input dataset that's already in the package, try `data(RandomVA5)`.

`causetextV5` has the codes you need, see the first and third column below:

```
> head(causetextV5)
     CAUSE.C.10  CAUSETXT.C40
[1,] "a_nrp"     "Not pregnant or recently delivered"
[2,] "a_pend_6w" "Pregnancy ended within 6 weeks of death"
[3,] "a_preg"    "Pregnant at death"
[4,] "b_0101"    "Sepsis (non-obstetric)"
[5,] "b_0102"    "Acute resp infect incl pneumonia"
[6,] "b_0103"    "HIV/AIDS related death"

[1,] "Not pregnant or recently delivered"
[2,] "Pregnancy ended within 6 weeks of death"
[3,] "Pregnant at death"
[4,] "01.01 Sepsis (non-obstetric)"
[5,] "01.02 Acute resp infect incl pneumonia"
[6,] "01.03 HIV/AIDS related death"
```

**Comment by rrwen** [comment]
Thanks - my apologies for misunderstanding!

I tried it with the correct data and it seems to work now - mapping all the output cause titles to titles with the codes:

```r
library(openVA)
library(CrossVA)
library(tidyverse)

# Convert WHO 2016 v1.5.1 data to OpenVA format
record_f_name <- system.file("sample", "who151_odk_export.csv", package = "CrossVA")
records <- read.csv(record_f_name, stringsAsFactors = FALSE)
output <- odk2openVA_v151(records)

# Run InSilicoVA 
model <- codeVA(
  data = output,
  data.type = "WHO2016",
  model = "InSilicoVA",
  Nsim = 10000,
  auto.length = FALSE
)

# Get InSilicoVA causes
isva_causes <- data.frame(cause = colnames(model$indiv.prob))

# Get WHO VA 2016 code title mappings
mappings <- causetextV5[,3]
names(mappings) <- causetextV5[,2]

# Remap InSilicoVA causes to have codes in titles
isva_remap <- isva_causes %>% mutate_all(~ recode(., !!!mappings))
isva_remap
```

## Side Note

It would be good to mention this in the guide or have a helper function for this - I couldn't find it in the docs, but maybe I didn't look in the right places?

I only found out about causetextV5 from a previous analysis file from Sam.

**Comment by richardli** [comment]
Great! Thanks, yes we could improve the document about this...on the todo list
