### ISSUE TITLE
Question: Data Dictionary for OpenVA Format

### ISSUE THREAD

**Issue by rrwen** [verbal-autopsy-software/openVA#34]
Hi @richardli 

I was wondering if:

1. There are column descriptions for the openva format?
2. The openva format columns can be matched back to the WHO 2016 V1.5.1 columns?

## Example

E.g. what does i370o and i371o mean?

```r
library(openVA)
library(CrossVA)
library(tidyverse)

# Convert WHO 2016 v1.5.1 data to OpenVA format
record_f_name <- system.file("sample", "who151_odk_export.csv", package = "CrossVA")
records <- read.csv(record_f_name, stringsAsFactors = FALSE)
output <- odk2openVA_v151(records)

# Are there column descriptions for the openva format?
# Can these columns be matched back to the WHO 2016 V1.5.1 columns?
colnames(output)
```

## Use Case

We are trying to determine which columns have the missing symptoms and data (InSilicoVA and InterVA5 revealed IDs with messages `Error in age indicator: Not Specified` and `Error in indicators: No symptoms specified`.

Since we had to convert from our raw format to WHO 2016 ODK format then to OpenVA, the column names are different than the ODK WHO 2016 format column names. Due to this, it is difficult to trace back which columns in our raw data are the issue.

```
raw --> odk_who_2016_v151 --> openva
```

**Comment by richardli** [comment]
For reference of other future users: 

What you are looking for is in the user guide of Peter Byass's InterVA software. You can download from this link: http://www.byass.uk/interva/products.htm

If you are looking for a clean data frame in R, you can get it by
```
> library(openVA)
> data(probbaseV5)
```
For example if you look at the top few rows
```
> probbaseV5[1:20, 1:3]
```

**Comment by rrwen** [comment]
Thanks! I found them in the appendix 1 of the InterVA-5.1 user guide by downloading the interva5 software as shown by @richardli:

http://www.byass.uk/interva/products.htm
> InterVA-5 version 5.1 (released 9th April 2020) can be downloaded [here](http://www.byass.uk/interva/interva5_1.zip)

Attaching for future users:

[InterVA-5.1 UG.pdf](https://github.com/verbal-autopsy-software/openVA/files/12243430/InterVA-5.1.UG.pdf)
